apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: default
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.targetPort }}
  type: LoadBalancer
