apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginx-cron
  namespace: handson
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - name: nginx
            image: nginx:latest
            command: ["date"]
          restartPolicy: Never
